### ISSUE TITLE
How do you populate API calls?

### ISSUE THREAD

**Issue by maxlinc** [oldarmyc/pitchfork#2]
When I install and run locally, the app comes up and I can login, but I don't have any available API calls:

![screen shot 2014-07-16 at 12 34 15 pm](https://cloud.githubusercontent.com/assets/896878/3602039/1edab2be-0d07-11e4-95b0-83135b268fd3.png)

How are you supposed to populate the database?

**Comment by davidscholberg** [comment]
@oldarmyc Those links for cloud_networks and ng_servers are dead. Are they at another location, or is there perhaps another way to import API calls?

**Comment by oldarmyc** [comment]
Working on getting an updated link list for all of the products and calls, to make it easier to import.

**Comment by oldarmyc** [comment]
Added to readme #55 on how to add all of the active product API calls with a download to the tar file
