### ISSUE TITLE
SSL certificate private keys stored on your systems

### ISSUE THREAD

**Issue by jamieburchell** [oldarmyc/pitchfork#56]
Hey

When using Pitchfork to add SSL certificates the private key is stored as a byproduct of facilitating the API call history log.

Ideally, this wouldn't be stored at all for security reasons (login compromised, database hacked, etc)

Failing that, a mechanism for clearing the history would be a step in the right direction.

**Comment by oldarmyc** [comment]
This is in progress, and will update once tested and deployed.

**Comment by oldarmyc** [comment]
PR #58 was deployed and tested. It is live on the public site, and can be utilized. The request data object will be removed and marked as such in the display.
