### ISSUE TITLE
agent.filesystem_state missing from select options

### ISSUE THREAD

**Issue by jamieburchell** [oldarmyc/pitchfork#68]
Is it possible to add "agent.filesystem_state" to the drop down of options when adding a Rackspace Monitoring check here https://pitchfork.cloudapi.co/monitoring/ ?

It does appear in the API response from "List Check Types" but not in the select options:

```
        {
            "category": "agent_system", 
            "fields": [], 
            "supported_platforms": [
                "Linux"
            ], 
            "type": "agent", 
            "id": "agent.filesystem_state", 
            "channel": "stable"
        }, 
```

**Comment by oldarmyc** [comment]
Added the state to the create and update calls.
