### ISSUE TITLE
Add server shutdown (not reboot) call to pitchfork

### ISSUE THREAD

**Issue by zippydaspinhead** [oldarmyc/pitchfork#69]
Hey all,

I realize the use case for this call is fairly small, but it would still be helpful.  Sometimes customers wish to shutdown servers temporarily, but not come back with a reboot right away.  Full shutdowns can also be used as troubleshooting steps beyond regular reboots for certain issues within OS or within the cloud infrastructure.  

I'd like to ask that this call be added to the calls currently available to cloud servers, as I believe this would help customers as well as Rackspace support personnel troubleshoot issues and improve ease of use for day to day operations as well by providing a wrapper for this call to less technically inclined customers.

The relevant API documentation for this call can be found at the provided link.

https://developer.rackspace.com/docs/cloud-servers/v2/api-reference/svr-basic-operations/#stop-specified-server

Thanks!
Jake Regan

**Comment by oldarmyc** [comment]
Call added: https://pitchfork.cloudapi.co/servers/#stop_server-cloud_servers
